CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4() UNIQUE NOT NULL,
    name VARCHAR(255) unique NOT NULL ,
    type VARCHAR(255) NOT NULL,
    price int,
    created_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMPTZ
);